name: "🪲 Report a Bug"
description: "Use this if something doesn't seem to work with an existing extension"
title: "Please insert the extension name and a short title"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Description"
      value: |
        **Reproduction Steps**
        
          1. ...
          2. ...
          
        **Expected Result**
        
          ...
          
        **Actual Result**
        
          ...
