name: "💡 Make a Suggestion"
description: "Use this for feature and change requests for existing extensions"
title: "please insert the extension name and a brief title here"
body:
  - type: textarea
    description: "(supports markdown)*
    validations:
      required: true
    attributes:
      label: "Description"
      value: |
        1. Problem description (aka. usecase motivation)
        ...
        2. Solution suggestion
        ...
