name: "💡 Make a Suggestion"
description: "Use this for feature and change requests for existing extensions"
title: "please insert extension name and a short title"
body:
  - type: textarea
    attributes:
      label: "Description"
      value: |
        1. Problem description (aka. usecase motivation)
        ...
        2. Solution suggestion
        ...
    validations:
      required: true
