name: "💡 Make a Suggestion"
description: "Use this for feature and change requests for existing extensions"
title: "Please insert the extension name and a short title"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Please describe your suggestion"
      value: |
        **Problem description (aka. usecase motivation)**
        
        ...
        
        **Solution suggestion**
        
        ...
