name: "🪲 Report a bug"
description: "Use this if something does not work"
title: "{{ extension-name }} + {{ you title }}"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Please describe the bug"
      value: |
        **Reproduction Steps**
        
          1. {{...}}
          2. {{...}}
          
        **Expected Result**
        
          {{...}}
          
        **Actual Result**
        
          {{...}}
