name: "💡 Make a suggestion"
description: "Use this for feature and change requests"
title: "{{extension name}} + {{your title}}"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: "Please describe your suggestion"
      value: |
        **Problem description (aka. usecase motivation)**
        
        {{...}}
        
        **Solution suggestion**
        
        {{...}}
