name: "🛟 Something else"
description: "Use this for anything that isnt a bug report or suggestion that relates to an existing extension"
title: "title"
labels: ["🛟 Support"]
body:
  - type: textarea
    attributes:
      label: "Description"
